/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim Anonymous Reports
         * @description Reassign an anonymous visitor's reports to the signed-in caller.
         */
        post: operations["claim_anonymous_reports_auth_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corpus Stats */
        get: operations["corpus_stats_corpus_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description The caller's own reports, newest first.
         *
         *     An explicit join rather than a relationship: `models.py` declares none, and
         *     async SQLAlchemy turns a forgotten eager-load into a runtime error.
         */
        get: operations["list_reports_reports_get"];
        put?: never;
        /** Create Report */
        post: operations["create_report_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{public_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_reports__public_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CitedTextBody
         * @description Serialization copy of both `Risk` and `DifferentiationAngle`.
         */
        CitedTextBody: {
            /** Sources */
            sources?: number[];
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** CompetitorBody */
        CompetitorBody: {
            /** Domain */
            domain?: string | null;
            /** Funding Stage */
            funding_stage?: string | null;
            /**
             * Name
             * @default
             */
            name: string;
            /** Sources */
            sources?: number[];
            /**
             * What They Do
             * @default
             */
            what_they_do: string;
        };
        /** CreateReportRequest */
        CreateReportRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Idea */
            idea: string;
            /** Target User */
            target_user?: string | null;
        };
        /** CreateReportResponse */
        CreateReportResponse: {
            /** Id */
            id: number;
            /** Public Slug */
            public_slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
        };
        /**
         * DuplicateError
         * @description You already ran this. Carries the slug so the UI can link to it.
         */
        DuplicateError: {
            /** Existing Slug */
            existing_slug: string;
            /**
             * Reason
             * @default duplicate
             * @constant
             */
            reason: "duplicate";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * QuotaError
         * @description Why a submission was turned away without spending anything.
         *
         *     `reason` is a closed set so the client's branch is exhaustive rather than
         *     guessed: these three mean genuinely different things to a user — "sign in
         *     to keep going", "you are out of runs this month", and "too many free runs
         *     from this address".
         */
        QuotaError: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "anon_quota" | "user_quota" | "ip_rate";
        };
        /**
         * ReportBody
         * @description What a stored report looks like on the way out.
         *
         *     Deliberately *not* `graph.schema.JudgeReport`, even though it mirrors it
         *     field for field. `JudgeReport` is a **generation** contract: strict on
         *     purpose (`risks` needs at least one entry, the verdict must be substantive)
         *     so a bad judge output fails the run rather than shipping. This is a
         *     **serialization** contract over rows that are already in the database.
         *
         *     Reuse the strict model here and any row written under older rules — a
         *     pre-rename `competitive_intensity`, a report with zero risks — turns a
         *     `GET` into a 500. The user's own paid-for report becomes unservable because
         *     of a rule that exists to police the LLM. Hence: same shape, no constraints,
         *     every list defaulting empty.
         *
         *     `tests/test_api_contract.py` asserts the field sets stay in step.
         */
        ReportBody: {
            /** Citations */
            citations?: string[];
            /** Competitors */
            competitors?: components["schemas"]["CompetitorBody"][];
            /** Degraded Agents */
            degraded_agents?: string[];
            /** Differentiation */
            differentiation?: components["schemas"]["CitedTextBody"][];
            /** Risks */
            risks?: components["schemas"]["CitedTextBody"][];
            subscores?: components["schemas"]["SubscoresBody"];
            /**
             * Verdict
             * @default
             */
            verdict: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Id */
            id: number;
            /** Public Slug */
            public_slug: string;
            report: components["schemas"]["ReportBody"] | null;
            /** Score */
            score: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Step */
            step: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReportSummary
         * @description History row. Deliberately not the full report: the body is tens of KB.
         */
        ReportSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Idea */
            idea: string;
            /** Public Slug */
            public_slug: string;
            /** Score */
            score: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
        };
        /**
         * SubscoresBody
         * @description Serialization copy of `Subscores`. No `ge`/`le` — see `ReportBody`.
         */
        SubscoresBody: {
            /**
             * Competitive Headroom
             * @default 0
             */
            competitive_headroom: number;
            /**
             * Feasibility
             * @default 0
             */
            feasibility: number;
            /**
             * Market Size
             * @default 0
             */
            market_size: number;
            /**
             * Novelty
             * @default 0
             */
            novelty: number;
            /**
             * Timing
             * @default 0
             */
            timing: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    claim_anonymous_reports_auth_claim_post: {
        parameters: {
            query?: never;
            header?: {
                "x-anon-id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corpus_stats_corpus_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_reports_reports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-anon-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_reports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-anon-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateReportResponse"];
                };
            };
            /** @description You already ran this idea recently. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Free run used, quota exhausted, or rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaError"];
                };
            };
        };
    };
    get_report_reports__public_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
